services:
  physiobuddy_authservice:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: physio_buddy_authserver
    working_dir: /app                       # Set the working directory inside the container
    ports:
      - "3000:3000"                         # Expose port 3000 to your local machine
           # The start command for your app
    depends_on:
      - db                                  # Ensure DB is started first
    volumes:                         # First you do git pull, then on running docker-compose up --build:
      - ./app:/app                 # this overwrites the content of ./app folder to the container
      - /app/node_modules           #this excludes the node_modules folder from overwriting the one inside the container
    command: ["npm", "run", "dev"]

    restart: on-failure

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: physio_buddy_db
    volumes:
      - postgres_auth:/var/lib/postgresql/data  # Persistent volume for DB data
    ports:
      - "5432:5432"                        # Expose PostgreSQL port


volumes:
  postgres_auth:  # Volume for PostgreSQL data
