apiVersion: v1
kind: Service
metadata:
  name: auth-server-service
  labels:
    app: auth-server
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: auth-server