name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_IMAGE_NAME: physiobuddy2024/physio_buddy_authserver
  DB_IMAGE_NAME: physiobuddy2024/physio_buddy_db

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create .env file
        run: |
          echo "${{ secrets.APP_ENV }}" > app/.env

      # Build and push app image
      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ env.APP_IMAGE_NAME }}:latest
            ${{ env.APP_IMAGE_NAME }}:${{ github.sha }}

      # Build and push db image
      - name: Build and push db image
        uses: docker/build-push-action@v5
        with:
          context: ./db
          file: ./db/Dockerfile
          push: true
          tags: |
            ${{ env.DB_IMAGE_NAME }}:latest
            ${{ env.DB_IMAGE_NAME }}:${{ github.sha }}